"""add dictionary entries table

Revision ID: 7f28fb0167d6
Revises: 7cd770701b1a
Create Date: 2026-07-22 19:36:43.733875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f28fb0167d6'
down_revision: Union[str, None] = '7cd770701b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.String(length=50), nullable=True),
    sa.Column('kanji', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reading', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('senses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_entries_id'), 'dictionary_entries', ['id'], unique=False)
    op.create_index('ix_dictionary_entries_kanji_gin', 'dictionary_entries', ['kanji'], unique=False, postgresql_using='gin')
    op.create_index('ix_dictionary_entries_reading_gin', 'dictionary_entries', ['reading'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dictionary_entries_reading_gin', table_name='dictionary_entries', postgresql_using='gin')
    op.drop_index('ix_dictionary_entries_kanji_gin', table_name='dictionary_entries', postgresql_using='gin')
    op.drop_index(op.f('ix_dictionary_entries_id'), table_name='dictionary_entries')
    op.drop_table('dictionary_entries')
    # ### end Alembic commands ###
